# Project docker compose file to start up Postgres database locally.

#  To run in the foreground
#  > docker-compose up
#
#  To run in the background and tail the logs
#  > docker-compose up -d
#  > docker-compose logs -f
#
#  Subsequent builds for any changes in dockerfile.
#  > docker-compose build

version: '3'
services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: tms-postgres-db
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
